Feature/#15  create form input components
ramsayinnovations/ramsay-ui pull request #16
Opened 2021-01-27 15:12 UTC by MaksymTaratuta55

closes #15

2021-01-28 08:59 UTC, thecodeclimber commented
@MaksymTaratuta55 

I have made a number of changes.  Please take a look at the changes and fix any errors and add any thoughts or comments that you have.

Also -- I want to add a `col` prop to the `InputBase` component.  I have added the details of how it works in a comment to `InputBase.jsx`.  Please take a look and add it.  Thanks.

2021-01-28 09:23 UTC, MaksymTaratuta55 commented
@thecodeclimber, updated

2021-02-01 14:39 UTC, thecodeclimber reviewed
Please take a look at the lat

2021-02-01 14:39 UTC, thecodeclimber commented on src/components/form/InputBase.jsx
> +  ]),
Please note these changes and let me know your thoughts.  My idea was to offer both options (a number or the full word) for the prop value.

2021-02-01 14:39 UTC, thecodeclimber commented on src/themes/form/form.js
> +const twoThirdsCol = tw`col-span-6 sm:col-span-4`
I assume this is the best way to do this -- please change if there is a better way.

2021-02-01 14:39 UTC, thecodeclimber commented on src/themes/form/form.js
> +      '2/3': twoThirdsCol
See previous two comments...

2021-02-01 19:52 UTC, MaksymTaratuta55 commented
Yeah, everything is ok

2021-02-01 20:58 UTC, thecodeclimber requested changes

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +    )}
Please pull in the `Label` component similar to how we do it in `Input.jsx`

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +  helpText,
Please change name to `help`.  Since there is only one help related prop there is no need to specify that it is text.

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +  id,
Please remove the `id` prop and just set the value of `id` to whatever value is set to the `name` prop.  Unless there is a need to have a different value for `id` then `name` then I prefer simplifying the component and having as few props as possible (without sacrificing functionality).

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +}) => (
We need to add the `error` prop and include the `Error` component (similar to the `Input.jsx` component).  

Also, please have all props in alphabetical order.  Indeed, please do this for all components.  It's a style that I like and that I find helpful at times.  Thanks.

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +    )}
Replace with `Help` component (again, like `Input.jsx`).

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +  </div>
Please add the `Error` component above this div (again, like in `Input.jsx`).

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +    wrapper: PropTypes.string,
Please change to `base` like in `Input.jsx`

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Select.jsx
> +          </Listbox.Label>
Please use the `Label` component here

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Select.jsx
> +              </Listbox.Button>
Please create a `SelectButton` component using the `Button` component as a foundation.  Then import that `SelectButton` component into this file [in other words, we are using a similar pattern that we used with `Input.jsx`

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Select.jsx
> +                {list.map((el) => (
Please create an `Options` component.  The options component should include both `Transition` as well as `Listbox.Options`

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Select.jsx
> +                  </Listbox.Option>
Please create an `Option` (singular).

2021-02-01 20:58 UTC, thecodeclimber commented on src/themes/form/select.js
> +};
Please update this file to match the new select components that we created (i.e., `Options`, `Option`, `SelectButton`, etc).  Please use the `form.js` file as a model for how to organize the styles.

Also -- please add this to the `form.js` file similar to how I ask you below to add `textarea` (see that comment for instructions.  Thanks.

2021-02-01 20:58 UTC, thecodeclimber commented on src/components/form/Textarea.jsx
> +const Textarea = ({
NOTE:  After I wrote most of the comments below, I realized that we need to create a `TextareaBase` component similar to the `InputBase` component.  We should then make the `Textarea` component similar to the `Input` component.  Please do and let me know if you have any questions.  Thanks.

2021-02-01 20:58 UTC, thecodeclimber commented on src/themes/form/textarea.js
> +};
Please move this to the `form.js` file.  `textarea` should be on the same level as `input`.  I.e.,:

```
form = {
 label: { ... },
input: { ... },
textarea: { ... },
help: { ... },
```

2021-02-02 09:36 UTC, MaksymTaratuta55 commented on src/components/form/Textarea.jsx
> +  id,
I think the better way is to add "id" and if "name" is absent, set "id" into "name". Because "id" should be unique but not "name"

2021-02-02 14:32 UTC, MaksymTaratuta55 commented
@thecodeclimber, updated

2021-02-03 14:45 UTC, thecodeclimber reviewed
@MaksymTaratuta55 

I am going to merge what we have done for now.  If we need further changes, we can do them later on.

2021-02-03 14:46 UTC, MaksymTaratuta55 commented
@thecodeclimber, sure

2021-02-03 14:55 UTC, merged